name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "docs/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/release.yml"
      - ".gitignore"
      - ".goreleaser.yml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "docs/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/release.yml"
      - ".gitignore"
      - ".goreleaser.yml"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
